#
# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---
- name: create docker build dir
  file: state=directory path={{ kibana_docker_build }}

# we don't have rsync for photon yet, so use copy.
# copy doesn't have exclude and fails on the .git dir, so
# we use the with_fileglob to avoid getting .git
- name: sync the docker image src to remote nodes
  copy: src={{ item }} dest={{ kibana_docker_build }} mode=755
  with_fileglob:
    - ../../../../containers/docker/kibana/*

- name: build the image
  async: 1000
  shell: cd {{ kibana_docker_build }} && /bin/bash ./build.sh

- name: docker run kibana
  docker:
    docker_api_version: "{{ docker_api_version }}"
    name: kibana
    image: vmware-opencloud/kibana
    memory_limit: "{{ memory_limit }}"
    restart_policy: always
    state: reloaded
    expose:
      - 5601
    ports:
      - 80:5601
    links:
      - elasticsearch:elasticsearch
